USE [master]
GO

/****** Object:  Database [Casino]    Script Date: 25.12.2021 2:38:21 ******/
CREATE DATABASE [Casino]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Casino', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Casino.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Casino_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Casino_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Casino].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Casino] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Casino] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Casino] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Casino] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Casino] SET ARITHABORT OFF 
GO

ALTER DATABASE [Casino] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Casino] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Casino] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Casino] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Casino] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Casino] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Casino] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Casino] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Casino] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Casino] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Casino] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Casino] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Casino] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Casino] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Casino] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Casino] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Casino] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Casino] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Casino] SET  MULTI_USER 
GO

ALTER DATABASE [Casino] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Casino] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Casino] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Casino] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Casino] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Casino] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Casino] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Casino] SET  READ_WRITE 
GO

